### ISSUE TITLE
Timed out running tests

### ISSUE THREAD

**Issue by darkcohiba** [learn-co-curriculum/phase-0-intro-to-js-2-objects-lab#14]
### Canvas Link

https://learning.flatironschool.com/courses/5262/assignments/219686?module_item_id=512208

### Concern

A student was working through this and it timed out when running learn test, her code matches the solution.

terminal example below;

`  1) employees
       updateEmployeeWithKeyAndValue(employee, key, value)
         "before each" hook for "returns an employee with the original key value pairs and the new key value pair":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/ebyanjamal3/Development/phase-0-intro-to-js-2-objects-lab/test/indexTest.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)`

**Comment by lizbur10** [comment]
Hi @darkcohiba ! This does occasionally happen, especially if the student is a WSL user. The solution is to increase the timeout threshold in the package.json file. I recommend increasing it to 15000ms and see if that does the trick. The student can continue to increase it incrementally if necessary.
