### ISSUE TITLE
Wrong assignment fork

### ISSUE THREAD

**Issue by Devincb93** [learn-co-curriculum/phase-0-intro-to-js-2-objects-lab#19]
### Canvas Link

https://learning.flatironschool.com/courses/6566/assignments/244881?module_item_id=576772

### Concern

When I go to fork the assignment from github, the link it provides is from phase 0 intro to objects instead of phase 1 objects lab. 

### Additional Context

![image](https://github.com/learn-co-curriculum/phase-0-intro-to-js-2-objects-lab/assets/135791102/5f60e5d9-ec05-4c3e-ab7b-ceb925498336)

**Comment by lizbur10** [comment]
Hi @Devincb93 ! There are some labs and lessons in Phase 1 that are repeated from Phase 0. It's material that we feel is especially important to understand before proceeding. If you are comfortable with the material, you are free to just skim or skip over them entirely. If you want to re-do any of the labs for additional practice you'll need to delete your fork and re-fork.

Sorry about the confusion! 💙

**Comment by Devincb93** [comment]
OK, thank you so much!
