### ISSUE TITLE
Incomplete test?

### ISSUE THREAD

**Issue by jasminbrooke** [learn-co-curriculum/phase-0-intro-to-js-2-objects-lab#5]
### Canvas Link

https://learning.flatironschool.com/courses/4976/assignments/161307?module_item_id=345714

### Concern

This lab tests for four functions, the two non-destructive tests don't check that the original object is not modified

**Comment by graciemcguire** [comment]
Hi @jasminbrooke! 

I'm having difficulty reproducing the issue, so I'm going to close it for now. The 2 non-destructive tests seem to be working on my end. 

If you think I closed this issue in error, I'd be happy to take a second look!

As always, thanks for contributing! 💙
