### ISSUE TITLE
once again, very frustrating 

### ISSUE THREAD

**Issue by joshtho** [learn-co-curriculum/phase-0-intro-to-js-2-objects-lab#6]
For this lesson in particular, I still don't understand if we are actually going to be writing obj, key, and value whenever we are writing real code, or if those are just placeholders to help you see and learn where they go. 

If the latter is true, then I feel it would have been more beneficial to learn this in the lesson, especially for people who are brand new to coding, like me. I would have rather seen this code explained to me in the lesson, and then the mondayMenu explainations to relate to it. Then maybe for the test make an employee list of my own with corrections ect.. I went in thinking that this would be the case, kind of like how the lesson showed you ie. mondayMenu tuesdayMenu ect.. but again like in previous lessons, the instructions weren't super clear to me.

I still have to look up pretty much everything on slack after my fifth attempt of looking at instructions and going back into the lesson and seeing almost no relevance to what the test wants. It is really frustrating and time consuming. I don't really feel like I'm prepared for these tests. 

Also, I'm still irked with how we're supposed to look at the index test.js and just "know" what it is were supposed to do. It's just not easy to read for me with the little info that was explained about it. I feel like no brand new coder is having an easy time with this. I want to learn, practice, and be confident with the material first before I test on my own without instructions. If the instructions were on the lesson, walking you through what to do, I think that would be wayyyy more helpful and less stressful.

**Comment by lizbur10** [comment]
Hi @joshtho! I'm sorry to hear that you're finding the lessons so frustrating! This content is very challenging, especially for people who are new to coding, and it takes a while for the concepts to really sink in and start to make sense. 

As for reading the tests, that too is a skill that takes time and practice to master. It's a good habit to get into to try looking at them - in particular, the description inside the 'it()' along with the errors you're getting - and it will get easier over time. 

If you find yourself getting really stuck and frustrated, I recommend that you make use of the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) function in Canvas to get help from a member of the Academic Success Team.

Thank you for providing your feedback - we will keep it in mind for upcoming releases of this curriculum.

As always, thanks for contributing! 💙
